var = input('Digite alguma coisa: ')
print('o tipo primitivo desse valor eh: ', type(var))
print('so tem espacos? ', var.isspace())
print('eh um numero? ', var.isnumeric())
print('eh alfabetico? ', var.isalpha())
print('eh alfanumerico? ', var.isalnum())
print('esta em maiusculo?  ', var.isupper())
print('esta em minusculo? ', var.islower())
print('esta capitalizada? ', var.istitle())
